/*
 * This file is generated by jOOQ.
 */
package demo.kireev.notificationsinkservice.jooq;


import demo.kireev.notificationsinkservice.jooq.tables.Notification;
import demo.kireev.notificationsinkservice.jooq.tables.OutboxEvent;
import demo.kireev.notificationsinkservice.jooq.tables.Payment;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.notification</code>.
     */
    public static final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public static final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.payment</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;
}
